Attendize/Attendize

public/user_content/.gitignore

Small fix that will prevent the empty `user_content` folder from being ignored by Git.
All files in the user_content folder will be ignored.

Enabled committing an empty user_content folder

---

resources/views/Shared/Partials/GlobalMeta.blade.php

When you don't run Attendize on a root domain (`http://localhost/attendize/public` for example) the `GlobalMeta.blade.php` file didn't generate the right path to the assets. 
Now using the `asset()` function for the right result.
Note: I also switched the sizes and href properties for the `icon` metatags. Just to have it in the same order as the `apple-touch-icon` metatags.

Fixed urls for Global Meta file

---

readme.md

Changed "weary" to "wary" because author is cautioning user against production use at this point.

docs: Correct vocabulary in README

---

app/Http/Controllers/EventOrdersController.php

I also fixed a float comparison bug. When i did a partial refund of 25 (total order 25.99) it worked. Then i tried to do another partial at .99 it kept saying the max i could do was .99 (which is what i was doing). Added rounding to 2 decimal places. If we ever support currencies with more than 2 decimal places this will need to be updated.

Removed duplicate refund code when issuing a partial refund

---

app/Helpers/macros.php
database/migrations/2014_03_26_180116_create_users_table.php
database/migrations/2016_03_16_193757_create_gateways_table.php
database/migrations/2016_03_16_213041_add_account_payment_id.php
database/migrations/2016_03_16_215709_add_gateway_id_accounts_table.php

- correctly removed foreign keys before removing columns
- turned off foreign key checks in initial migration to allow tables to
be dropped

Migration clean ups to ensure rollbacks work correctly.

---

app/Models/Order.php

Add dirname function in order to avoid to create a blank folder with the filename.

Fix issue when creating blank folder with filename

---

resources/views/ManageAccount/Modals/EditAccount.blade.php

Hey. I noticed that there were several elements with the if "general", and it bugged the account settings modal. I simply added a suffix to prevent this issue from happening again.
Documentation of the issue: [Video](https://www.youtube.com/watch?v=QbeKxNKyZAE)

Fix for non-unique modal IDs

---

app/Http/Kernel.php

The original original cookie middleware is no longer located in app/http/middleware, so the location has been updated to the Laravel default location.

Fixes Laravel issue with Cookie Middleware

---

resources/views/Public/ViewEvent/Partials/EventTicketsSection.blade.php

This seems like a more sensible default. Not sure what the zero option was for though.

Make 1 the default ticket quantity if there is only one ticket type

---

app/Models/Event.php

Corrected a typo in a function name in the Event model.

Correct typo in Event Model method

---

app/Http/Controllers/EventTicketsController.php
app/Http/Controllers/EventViewController.php
app/Http/Controllers/EventViewEmbeddedController.php
resources/views/Public/ViewEvent/Partials/EventCreateOrderSection.blade.php

Display as raw HTML after escaping and nl2br:
With current code, `<br/>` will be displayed instead of a line break. This commit fixes the issue.
Make tickets be sorted in ASC order:
In EventTicketsController::postUpdateTicketsOrder, sort_order is generated in ascending order, however, when displaying tickets, tickets is sorted in descending order. 964e456 tries to solve the issue but it is the other way around.

Two bugfixes

---

app/Http/Controllers/EventCheckoutController.php

Added 'receipt_email' to the Stripe charge creation request so customers get a payment receipt as well as their tickets. Also removed a blank line.
I would still like to see the $order->order_reference in the description, but I'm not sure if $order has that property at this point: line 330 of EventCheckoutController.php.

Update EventCheckoutController.php : stripe receipts.

---

app/Http/Controllers/EventAttendeesController.php
app/Http/Controllers/EventOrdersController.php

When an Attendee is cancelled, also remove the Attendee from the stats, to prevent errornous amounts for the event being shown.

Reflect Attendee cancellation in event stats

---

public/vendor/chartjs/readme.md
public/vendor/curioussolutions-datetimepicker/README.md

GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1

Fix broken headings in Markdown files

---

config/database.php

`port` variable in mysql has been set twice. So, removed the redundant variable.

port variable set twice

---

app/Http/Controllers/EventOrdersController.php

The function postMessageOrder should get datas from Orders not attendees table but orders table on line 437.
So I have fixed it.
I would be happy if I could get your feedback.

fix bug where postMessageOrder gets datas of orders table

---

app/Mailers/AttendeeMailer.php

Added condition to check if attribute `is_cancelled` for attendee is set to false before sending email.

fixes #376 Sending message to all attendees sends also to cancelled ones

---

resources/lang/fr/User.php

There is a small typo in a french locale file causing HTTP 500 errors on login.

Small typo fix causing 500 error when using french locale

---

app/Http/Controllers/EventCheckoutController.php

Addresses #409 .
The remaining tickets are calculated by subtracting the ordered tickets and the reserved tickets from the available tickets. Currently ordered tickets are counted twice before their corresponding reserved tickets have expired. Therefore in this PR we delete the user's reserved tickets once they've successfully bought ordered the tickets.

Remove reserved tickets once bought

---

app/Http/Controllers/InstallerController.php

Addresses #458 (and related #524). Forces the application key to be generated.
The `STDIN` error is caused by artisan which expects an input:
```
$ php artisan key:generate
**************************************
*     Application In Production!     *
**************************************
Do you really wish to run this command? (yes/no) [no]:
> 
```
We can bypass having to enter an input by forcing the key to be generated.

Force key generate in installer

---

app/Http/Controllers/EventController.php
app/Http/Controllers/EventCustomizeController.php
resources/lang/en/ManageEvent.php
resources/views/ManageEvent/Partials/EditEventForm.blade.php

Event currencies were previously only saved upon event creation and weren't able to be updated.  You can now change currency at the event level.

manage event currency

---

public/assets/javascript/check_in.js
resources/views/ManageEvent/CheckIn.blade.php

this works for me with ios 12.2 and safari. chrome on iphone does not work. 
not familiar with `getUserMedia`, but at least one browser works now.

fix(qr-code scanning)

---

app/Http/Controllers/EventCheckInController.php
config/attendize.php
resources/views/ManageEvent/Customize.blade.php
resources/views/ManageEvent/Modals/MessageAttendees.blade.php
resources/views/ManageEvent/PrintAttendees.blade.php
resources/views/ManageOrganiser/Dashboard.blade.php
resources/views/ManageOrganiser/Events.blade.php
resources/views/Shared/Partials/GlobalFooterJS.blade.php

This fixes missing environment values when using `php artisan config:cache` as this should be done in production.

Move env to config files

---

resources/views/en/Emails/messageReceived.blade.php

I have noticed that the email CONTACT form on the event page is broken.
Can see an error from the log:
```
[2019-06-09 05:50:00] production.ERROR: syntax error, unexpected '!', expecting ',' or ')' (View: /opt/bitnami/apps/attendize/resources/views/en/Emails/messageReceived.blade.php) {"userId":1,"exception":"[object] (ErrorException(code: 0): syntax error, unexpected '!', expecting ',' or ')' (View: /opt/bitnami/apps/attendize/resources/views/en/Emails/messageReceived.blade.php) at /opt/bitnami/apps/attendize/storage/framework/views/7636d50489ed84fa18df11267aa8e9453a5a7392.php:6, Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected '!', expecting ',' or ')' at /opt/bitnami/apps/attendize/storage/framework/views/7636d50489ed84fa18df11267aa8e9453a5a73 …
```

Fix bug in en messageReceived email template

---

app/Http/Controllers/EventCheckoutController.php
app/Http/Controllers/EventOrdersController.php
app/Http/Controllers/ManageAccountController.php
app/Http/routes.php
app/Models/PaymentGateway.php
app/Services/PaymentGateway/Dummy.php
app/Services/PaymentGateway/Factory.php
app/Services/PaymentGateway/Stripe.php
app/Services/PaymentGateway/StripeSCA.php
composer.json
composer.lock
database/migrations/2019_09_04_075835_add_default_gateways.php
public/assets/javascript/app-public.js
public/assets/javascript/frontend.js
resources/lang/en/Order.php
resources/lang/en/Public_ViewEvent.php
resources/views/ManageAccount/Partials/PaymentGatewayOptions.blade.php
resources/views/ManageAccount/Partials/Stripe.blade.php
resources/views/ManageAccount/Partials/StripeSCA.blade.php
resources/views/ManageEvent/Modals/ManageOrder.blade.php
resources/views/Public/ViewEvent/EventPageCheckout.blade.php
resources/views/Public/ViewEvent/EventPagePayment.blade.php
resources/views/Public/ViewEvent/Partials/Dummy.blade.php
resources/views/Public/ViewEvent/Partials/EventCreateOrderSection.blade.php
resources/views/Public/ViewEvent/Partials/EventPaymentSection.blade.php
resources/views/Public/ViewEvent/Partials/OfflinePayments.blade.php
resources/views/Public/ViewEvent/Partials/PaymentStripe.blade.php
resources/views/Public/ViewEvent/Partials/PaymentStripeSCA.blade.php

1. Removed dependencies on $gateway->id in the database which made the codebase fairly brittle in places. Use the name field of payment_gatway instead.
2. Refactored Event Checkout so that in theory it should be a lot easier to add other Omnipay gateways.
3. Removed Paypal Express as a gateway supported by default.
4. Payment Gateways Templates are now configurable by specifying an admin and checkout template in the database directly.
5. Broke each payment option out into its own template instead of trying to handle all payment gateways in one form with funny if conditions.
6. Account settings for Payment Gateways is now dynamic based on what is in the database.
7. Added migration and updated Seeder to make sure the payment_gateways is correct on in stall and when upgrading.
8. Updated …

Added Stripe SCA payment gateway as an option. 

---

app/Http/Controllers/EventCheckoutController.php
app/Services/PaymentGateway/Dummy.php
app/Services/PaymentGateway/Stripe.php
app/Services/PaymentGateway/StripeSCA.php
database/migrations/2019_09_18_082447_disable_refunds_on_stripe_sca.php

Currently refunds is not implemented on the Stripe SCA payment intents gateway.
Therefore refunds will have to be done manually from the stripe Dashboard.

Disable refunds on Stripe

---

resources/views/Public/ViewOrganiser/Partials/EventListingPanel.blade.php

Fixed the bug: when all events are private, "There are no Upcoming/Past events to display" boxes won't display

Patch for Organizer View

---

resources/lang/en/Public_ViewEvent.php

This commit fixes a misspelling of the word "continue" which users encounter while buying tickets.

fixed spelling in word "continue"

---

.github/workflows/laravel.yml

Small chore to setup github actions to run tests on push operations. This will alleviate some manual testing and start the foundation for automating a bunch of other maintenance things.
We are limiting the actions to `next` only for the time being. Will open it up to everything when `next` is merged into master.

Create first pass at Github actions to run tests on next branch

---

app/Http/Controllers/EventCheckInController.php

Right now, when you use the check-in function to read the generated QR-CODES of the `private_reference_number` value, you won't get the resulting attendee back from the search. With this change, this search criteria will be added.

Allow checking in with private reference number

---

app/Http/Controllers/EventCheckoutController.php
public/assets/javascript/app-public.js
public/assets/javascript/frontend.js

The iframe widget is great for embedding specific events into a different website. The checkout flow after that is a bit weird where humans have to try and follow the payment steps inside of an iframe which is not ideal. This might cause a lot of trust and dropoff issues. We aim to fix that by allowing people to hit the registration parts inside of the widget but the subsequent steps after that will open in the parent attendize window.
This change keeps the session data.
- Allow for the widget registration to pen the checkout steps in a parent window

Move registration step to the parent window

---

public/assets/javascript/app.js
public/assets/javascript/backend.js
resources/views/ManageOrganiser/Modals/CreateEvent.blade.php

The event create modal UI has some issues that occurred with the next changes. This PR aims to solve 2 of those UI issues where the create screen just hangs on errors.
- There were issues displaying form errors on required fields and the UI would hang indefinitely which provided a bad user experience. It now shows the error messages again and also supports the wysiwyg description box as an element.
- We needed to simplify the event venue address form elements to show the plain input boxes if the `google_maps_geocoding_key` was missing from the `.env`.  It will now only show the static form fields if the key is missing.
- Fix form errors not showing up on server error message responses
- Support error handler for wysiwyg textarea inputs as well
- Add check for …

Event create UI form error handling

---

resources/views/ManageEvent/Modals/CancelAttendee.blade.php
resources/views/ManageEvent/Modals/CancelOrder.blade.php
routes/web.php

If a user selects offline payment when checking out, when you go to the event orders page and click on cancel at the top it says `Cancelling the order will refund the selected attendees`. We shouldn’t show that message for orders which are awaiting payment.
This also counts for cancelling an attendee.
- Fixed a couple of named route parameter regressions
- Updated the cancel order to hide refund information if the order used offline payment method
- Updated the cancel attendee to hide refund information if the order used offline payment method

Offline Payments Copy Fixes

---

app/Exports/AttendeesExport.php
app/Exports/OrdersExport.php
app/Http/Controllers/EventAttendeesController.php
app/Http/Controllers/EventOrdersController.php
app/Imports/AttendeesImport.php
app/Models/Order.php
app/Models/OrderItem.php
config/app.php
resources/lang/en/Attendee.php
resources/lang/en/Ticket.php
resources/views/ManageOrganiser/Customize.blade.php

There has been some regressions with the laravel 6 upgrade so here is a PR to fix the niggles as they got found during the last rounds of testing `next`.
- Fixed the regression for `Excel` exports not working. [The version bump was a breaking change](https://docs.laravel-excel.com/3.1/getting-started/upgrade.html#upgrading-to-3-from-2-1)
- Removed the `sales_volume` increment on the `events` table since the field does not exist anymore
- Added back the `Excel` facade alias and service provider
- Added new translated strings for export columns
- Fixed the Organizer customize UI that had a failed route parameter in due to copy pasta
- Fixed the attendee bulk invite importer
**Orders Export**
**Attendees Export**

General regression fixes after laravel 6 upgrade

---

app/Http/Controllers/EventAttendeesController.php
app/Http/Controllers/EventOrdersController.php
app/Http/Controllers/EventViewController.php
app/Http/Controllers/ManageAccountController.php
app/Http/Controllers/UserSignupController.php

This PR adds much needed prefixes inside controllers to use locale-specific email templates. Without it, all emails are sent in English

added locale prefix to email templates calls inside controllers

---

composer.lock

As I mentioned in [this comment](https://github.com/Attendize/Attendize/issues/856#issuecomment-873557370) framework needs to be updated for newer composer. I did updating only it and collisions by doing: `composer update laravel/framework:^6.18.7 league/commonmark doctrine/inflector`
Two last dependencies are direct dependencies of `laravel/framework` so we can expect them to be tested by laravel devs.
Diff of composer info basically looks like this:
<details>
<summary>diff</summary>
```diff
-doctrine/inflector 1.3.1
+doctrine/inflector 2.0.3
---
-erusev/parsedown 1.7.4
---
-laravel/framework v6.13.1
+laravel/framework v6.18.14
---
-league/commonmark 1.2.2
-league/commonmark-ext-table v2.1.0
+league/commonmark 1.6.5
```
</details>
I went over what changed between those versions and only …

Updated laravel framework to support composer v2
