.gitignore
app/Http/Controllers/UserLoginController.php
app/Http/Controllers/UserSignupController.php
app/Models/Account.php
app/Models/User.php
readme.md
resources/lang/en/validation.php
resources/views/Public/LoginAndRegister/ForgotPassword.blade.php
resources/views/Public/LoginAndRegister/Login.blade.php
resources/views/Public/LoginAndRegister/ResetPassword.blade.php
resources/views/Public/LoginAndRegister/Signup.blade.php
resources/views/Shared/Partials/GlobalMeta.blade.php

Big update. Mainly syntax and some minor improvements in error messaging.
Used more of Laravel's functionality.

Login signup update

---

app/Http/Controllers/EventAttendeesController.php
app/Http/routes.php
app/Models/Attendee.php
public/user_content/.gitignore
resources/views/ManageEvent/Attendees.blade.php
resources/views/ManageEvent/Modals/ResendTicketToAttendee.blade.php
storage/cache/.gitignore

- Added routes
- Changed Attendees.blade to add a button group instead of just the
message button. Added message button to button group

Resend Ticket Email

---

public/user_content/event_images/.gitignore
resources/views/Public/ViewEvent/Partials/EventCreateOrderSection.blade.php
resources/views/Public/ViewEvent/Partials/EventViewOrderSection.blade.php
resources/views/Public/ViewEvent/Partials/PDFTicket.blade.php

Added Refunded Amount to Order Details view
Removed cancelled tickets from EventTickets View
Corrected first year for CC

Viewing cancelled order

---

app/Models/Account.php
app/Models/Activity.php
app/Models/Affiliate.php
app/Models/Attendee.php
app/Models/Currency.php
app/Models/DateFormat.php
app/Models/DateTimeFormat.php
app/Models/Event.php
app/Models/EventImage.php
app/Models/EventStats.php
app/Models/Message.php
app/Models/MyBaseModel.php
app/Models/Order.php
app/Models/OrderItem.php
app/Models/OrderStatus.php
app/Models/Organiser.php
app/Models/Question.php
app/Models/QuestionType.php
app/Models/ReservedTickets.php
app/Models/Ticket.php
app/Models/Timezone.php
app/Models/User.php

Adds missing docblocks to model classes.

Adds docblocks to models

---

resources/views/ManageEvent/Attendees.blade.php
resources/views/ManageEvent/CheckIn.blade.php
resources/views/ManageEvent/Customize.blade.php

A few layout fixes
Fixed the css for the Check In page so you can actually see the search box. 
Fixed issue when searching for a person already checked it, it wasn't displaying the check mark, but when you clicked it, it would tell you they were already checked in

Layout fixes

---

composer.json
composer.lock
database/factories/ModelFactory.php

- Adds the fzaninotto/faker library
- Adds several model factories to be used during tests.
Please scrutinize the data being generated. Many of the models aren't filled in yet, so I had to look to the migrations file for an idea of what data should be generated by the factory models. If you find any errors, let me know and I'll correct them.

Add model factories

---

app/Http/Controllers/EventQuestionsController.php
app/Http/Controllers/MyBaseController.php
app/Http/Requests/StoreEventQuestionRequest.php
app/Http/routes.php
app/Models/Question.php
app/Models/QuestionOption.php
app/Models/Ticket.php
database/migrations/2016_03_26_103318_create_attendees_questions.php
database/seeds/DatabaseSeeder.php
database/seeds/QuestionTypesSeeder.php
public/assets/javascript/backend.js
resources/views/ManageEvent/Customize.blade.php
resources/views/ManageEvent/Modals/EditQuestion.blade.php

- Created a migration (based on @daveearley 's migration) to add the
question_types, questions, question_options, event_question and
question_ticket tables.
- Created a seeder for the question_types table.
- Implemented event question add modal.
- Done a bit of refactoring to the ajax form submission error handling.
- Questions are now displayed on the event customization page, under the
Order form tab.

Made a start on implementing the 'Attendees Question' feature.

---

app/Exceptions/Handler.php
app/Providers/AuthServiceProvider.php
composer.json
composer.lock
config/app.php
config/attendize.php
config/auth.php
config/compile.php
config/mail.php
database/migrations/2014_03_26_180116_create_users_table.php
database/migrations/2014_10_12_100000_create_password_resets_table.php
database/migrations/2014_11_07_132018_add_affiliates_table.php
database/migrations/2014_11_17_011806_create_failed_jobs_table.php
database/migrations/2016_03_16_193757_create_gateways_table.php

Fixes #53 
Listed below are the changes made according to the upgrade guide at https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0. For details of a particular change, refer to the upgrade guide and look for the section with the same name as one of the bulleted items below.
- Updating Dependencies
- Authentication
- Configuration File
- Authorization
- Composer Class
- Configuration
- Environment Value
- Compiled Classes
- Database
- MySQL Dates
- Exception Handling
- Mail
- Service Providers

Updates Laravel to 5.2

---

readme.md

Add my name to the contributors.

Add myself to the contributors

---

app/Http/Controllers/EventAttendeesController.php
app/Http/routes.php
resources/views/ManageEvent/Attendees.blade.php
resources/views/ManageEvent/Modals/ImportAttendee.blade.php

csv file import -- just a starting point needs expanding

Event Attendee Import

---

app/Http/Controllers/EventCheckoutController.php
app/Models/EventStats.php
database/migrations/2014_03_26_180116_create_users_table.php

Those are some changes I had to make to have Attendize run with postgresql.
I did not test all the screens/functionalities so additional changes may be required.

Postgres compatibility

---

app/Http/Controllers/EventCheckoutController.php
app/Models/EventStats.php
database/migrations/2014_03_26_180116_create_users_table.php

Reverts Attendize/Attendize#79 due to issue #80

Revert "Postgres compatibility"

---

app/Http/Controllers/EventCheckoutController.php
app/Models/EventStats.php
database/migrations/2014_03_26_180116_create_users_table.php

Reverts Attendize/Attendize#81

Revert "Revert "Postgres compatibility""

---

app/Http/Controllers/EventAttendeesController.php
app/Http/Controllers/EventCustomizeController.php
database/migrations/2014_03_26_180116_create_users_table.php
database/migrations/2016_03_25_114646_organiser_page_design_update.php

Some fixes for postgres compatibility

Postgresql compatibility

---

config/services.php

Laravels TransportManager needs this line for Sparkpost Mail

Allows for Sparkpost to be used as Mail client

---

app/Http/Controllers/EventAttendeesController.php
database/migrations/2016_06_14_115337_add_is_refunded_column_to_attendees.php
resources/views/Emails/notifyRefundedAttendee.blade.php
resources/views/ManageEvent/Modals/CancelAttendee.blade.php
resources/views/ManageEvent/Modals/ManageOrder.blade.php

Can now refund individual tickets, for their CURRENT PRICE. (It doesn't store ticket-price when they're purchased, so they will be refunded the current value that a ticket is set to be sold for).

Allow Refunds of individual tickets

---

public/assets/javascript/app-public.js
public/assets/javascript/frontend.js

For some odd reason, this was left out of the frontend, but implemented in App.js and Backend.js

Allow Ajax Validation errors in Frontend.js

---

app/Http/Controllers/EventAttendeesController.php
app/Http/Controllers/EventController.php
app/Http/Controllers/ManageAccountController.php
app/Http/Controllers/OrganiserController.php
app/Http/Controllers/UserLoginController.php
app/Http/Middleware/FirstRunMiddleware.php
app/Http/routes.php
app/Models/MyBaseModel.php
app/Models/OrderStatus.php
app/Models/TicketStatus.php
config/database.php
database/factories/ModelFactory.php
database/migrations/2016_05_25_145857_attendee_ref_fix.php
resources/views/ManageEvent/Modals/EditTicket.blade.php
resources/views/ManageEvent/Partials/EditEventForm.blade.php
tests/EventAttendeesTest.php
tests/EventTest.php
tests/OrganiserTest.php
tests/TestCase.php
tests/UserTest.php

Hi Dave/Others. Just adding this in to get some feedback. 
I've added a couple of tests in and want to know if i'm on the right track. Added an ajax test for creating event. Could you take a look and tell me if it's the way you want to go forward with it, and give me and pointers. 
I've also found a couple of routes that are no longer used (showEditOrganiser, postEditOrganiser), seems to use Customise now instead. 
Found a few issues with Response:: being called which caused errors for me, so switched to response()
Apart from those it's just test changes. I will try and do a couple a day to give us at least some test coverage

Started Adding Tests. 

---

app/Http/Controllers/UserController.php
resources/views/ManageUser/Modals/EditUser.blade.php
tests/UserLoginTest.php
tests/UserSignUpTest.php
tests/UserTest.php

Have fixed the edit user validations and added a test

Fixed Edit User

---

public/assets/javascript/app-public.js
public/assets/javascript/frontend.js

Function already existed, call that instead of manually writing it out.

Replaced manual function with existing one.

---

config/modules.php
modularity.md

Fixed up the documentation a bit

Modularity

---

app/Http/Controllers/EventCheckoutController.php
resources/views/ManageEvent/Customize.blade.php
resources/views/ManageEvent/Partials/EditEventForm.blade.php

Without this, you woud get an exception further down in the code that would result in an exception when giving a non-set variable to the foreach loop.

Fix no tickets selected returns an exception

---

app/Http/Controllers/EventViewController.php
app/Http/routes.php
app/Models/Event.php
resources/views/Mailers/TicketMailer/SendOrderTickets.blade.php

Add the ability to download an ICS file for the event, this link is provided in the ticket confirmation email.

Add user importable calendar to email

---

app/Http/Controllers/OrganiserCustomizeController.php
database/migrations/2016_09_16_221455_add_google_analytics_code_to_organiser.php
resources/views/ManageOrganiser/Customize.blade.php
resources/views/Public/Partials/ga.blade.php
resources/views/Public/ViewOrganiser/Layouts/OrganiserPage.blade.php
resources/views/Public/ViewOrganiser/OrganiserPage.blade.php

Allow each organiser to use a different Google Analytics code.

Per Organiser Google Analytics

---

app/Models/Account.php
app/Models/AccountPaymentGateway.php
app/Models/Attendee.php
app/Models/Currency.php
app/Models/Event.php
app/Models/Message.php
app/Models/Order.php
app/Models/Organiser.php
app/Models/Question.php
app/Models/QuestionAnswer.php
app/Models/QuestionOption.php
app/Models/Ticket.php
app/Models/User.php

Model FQN written instead of class name string

---

public/assets/javascript/app-public.js
public/assets/javascript/frontend.js

when toggle between offline and online payment methods.

Correctly disable and un-disable fields

---

resources/views/Public/ViewEvent/Partials/EventCreateOrderSection.blade.php

Fixed typo

---

app/Http/Controllers/EventAttendeesController.php
app/Http/Controllers/EventOrdersController.php
app/Http/routes.php
resources/views/ManageEvent/Modals/CancelOrder.blade.php
resources/views/ManageEvent/Modals/EditOrder.blade.php
resources/views/ManageEvent/Modals/ManageOrder.blade.php

Edit an order [firstname, lastname and Email]
Resend an entrire order (especially useful if someone entered a wrong email which has then beed edited)
Show ticket reference in the order refund modal, so you can quickly refund/cancel multiple tickets in an order

Edit an order

---

app/Http/Controllers/OrganiserController.php
app/Http/Controllers/OrganiserCustomizeController.php
app/Models/Organiser.php

* Preserve Aspect Ratio
* Use the same size no matter where the upload is happening

Uniform Organiser Image Upload

---

database/seeds/CurrencySeeder.php

A space is the norm for some currency symbols

Add Whitespace to selected currencies

---

.env.example
Dockerfile-php
docker-compose.yml
readme.md

- Change .env.example to use postgres, cause in docker compose file, postgres sql is being used
- Change php base image to php:7.0-fpm, cause using latest will have compatible issue
- Rewrite docker-compose file to version 2
- Modify readme docker section, cause some of the steps are wrong

fix docker-compose setup configurations

---

app/Attendize/Repositories/Repository.php
app/Http/Controllers/EventCheckoutController.php
app/Models/AccountPaymentGateway.php
app/Providers/AppServiceProvider.php
resources/views/ManageEvent/Dashboard.blade.php
resources/views/ManageOrganiser/CreateOrganiser.blade.php

I think we should use Request method to get first_run

use Request method to get first_run

---

resources/lang/en/Controllers.php
resources/lang/pl/Controllers.php

As described here - https://github.com/Attendize/Attendize/commit/dec455c38919cc2562c8d02e951994d27f0af068#comments
confirmed that it fixes email subjects for attendee mails

Fix attendee email subject

---

resources/lang/en/Organiser.php

fix untranslated string

---

app/Http/Controllers/EventAttendeesController.php
resources/lang/en/Email.php
resources/lang/pl/Email.php

Fix issue with inviting attendees

---

app/Models/Event.php
resources/views/Public/ViewEvent/Partials/AttendeeQuestions.blade.php

HI, I found one bug after I updated to larval 5.6.
Files which related to surveys were not updated from ->list to ->pluck.

445 fix surveys bug after updating to L5.6

---

resources/lang/en/basic.php
resources/lang/pl/basic.php

This fixes stops upcoming events from showing one month extra in the future.

Fixes #414 #450 #434

---

app/Http/Controllers/EventAttendeesController.php
resources/views/ManageEvent/Modals/EditQuestion.blade.php

Fixes server error when trying to import a CSV of invitees

Fix issue where taxamt not set after import

---

app/Http/Controllers/EventCheckInController.php
app/Http/Controllers/InstallerController.php
public/assets/javascript/check_in.js
public/assets/stylesheet/check_in.css
resources/lang/en/Attendee.php
resources/lang/en/Controllers.php
resources/lang/pl/Attendee.php
resources/lang/pl/Controllers.php
resources/views/ManageEvent/CheckIn.blade.php

This PR is a continuation from #476

Fix vulnerabilities

---

app/Http/Controllers/RemindersController.php
app/Http/routes.php
app/Models/User.php
app/Notifications/UserResetPassword.php
config/app.php
resources/views/en/Emails/Auth/Reminder.blade.php

Fixes the forgotten password link and sends link to reset password

fixes #470

---

app/Http/Controllers/EventCheckoutController.php

The logic here made an important part of the codebase hard to read so just modified it slightly.
Goal is to refactor this controller at some point

modified logic slightly

---

resources/views/ManageEvent/Dashboard.blade.php

Fixes error where charts on Dashboard displayed incorrect dates.  
Fixes a javascript error which expected an element to exist which did not.

fixes #501 

---

database/factories/ModelFactory.php

This is a generally a prerequisite for unit tests.

Fix Model Factory

---

app/Http/Controllers/EventCheckoutController.php
app/Http/routes.php
resources/lang/en/Event.php

Continuation from #495

---

resources/views/Shared/Layouts/Master.blade.php

Fixing feedback URL

---

resources/views/ManageEvent/Customize.blade.php
resources/views/ManageEvent/Dashboard.blade.php
resources/views/ManageOrganiser/Dashboard.blade.php
resources/views/ManageOrganiser/Events.blade.php

Nits (https and fix a dev console warning)

---

resources/views/en/Emails/messageReceived.blade.php

Fix for "Message" contains html tags #574

---

.gitignore
app/Models/Attendee.php
app/Models/Order.php
composer.lock
database/migrations/2019_04_05_180853_change_private_reference_number_column_type.php

This changes the Private Reference Number (Data in QR Code), less chance of getting double ID's and I think its more secure.

Change Private Reference Number

---

app/Http/Controllers/EventController.php
app/Http/Controllers/EventDashboardController.php
app/Http/Controllers/IndexController.php
app/Http/api_routes.php
app/Http/routes.php

* `php artisan route:cache` now works 🚀 
* Fixed 1 Todo
* Removed the sample API route `/`

Remove closures on route files

---

readme.md

Dashboard details

---

.env.example

Reverts Attendize/Attendize#701

Revert "Update .env.example"

---

resources/views/Installer/Installer.blade.php

Improved the test database connection link and made it a button

Improved the test database connection button

---

resources/views/ManageEvent/Modals/MessageOrder.blade.php
resources/views/ManageEvent/Orders.blade.php

'event_id' was missing from two routes.

bugfixes in routes

---

Dockerfile-composer
Dockerfile-php
app/Cancellation/OrderCancel.php
app/Cancellation/OrderCancellation.php
app/Cancellation/OrderRefund.php
app/Cancellation/OrderRefundAbstract.php
app/Http/Controllers/EventCheckoutController.php
app/Mailers/OrderMailer.php
resources/lang/en/Order.php
resources/views/Public/ViewEvent/Partials/EventPaymentSection.blade.php

1. Allow Pay offline orders to be cancelled.
2. Fixed bug where if the order requires payment the offline payments option is shown if enabled.
3. Upgrade docker images to PHP7.3
4. Changed Cancel/Refund button to just cancel to remove ambiguity.

finge case bug fixes

---

app/Helpers/strings.php
app/Http/Controllers/EventAccessCodesController.php
app/Http/Controllers/EventAttendeesController.php
app/Http/Controllers/EventCheckoutController.php
app/Http/Controllers/EventController.php
app/Http/Controllers/EventCustomizeController.php
app/Http/Controllers/EventTicketsController.php
app/Http/Controllers/EventViewController.php
app/Http/Controllers/OrganiserController.php
app/Http/Controllers/OrganiserCustomizeController.php
app/Models/Event.php
config/purifier.php
resources/views/ManageEvent/Dashboard.blade.php
resources/views/ManageOrganiser/CreateOrganiser.blade.php
resources/views/ManageOrganiser/Customize.blade.php
resources/views/ManageOrganiser/Dashboard.blade.php
resources/views/ManageOrganiser/Events.blade.php
resources/views/ManageOrganiser/Partials/EventCreateAndEditJS.blade.php
resources/views/ManageOrganiser/Partials/OrganiserCreateAndEditJS.blade.php
resources/views/Public/ViewEvent/Layouts/EmbeddedEventPage.blade.php
resources/views/Public/ViewEvent/Layouts/EventPage.blade.php
resources/views/Public/ViewEvent/Partials/EventDescriptionSection.blade.php
resources/views/Public/ViewEvent/Partials/EventOrganiserSection.blade.php
resources/views/Public/ViewEvent/Partials/EventShareSection.blade.php
resources/views/Public/ViewEvent/Partials/EventViewOrderSection.blade.php
resources/views/Public/ViewEvent/Partials/OfflinePayments.blade.php
resources/views/Public/ViewOrganiser/Layouts/OrganiserPage.blade.php
resources/views/Public/ViewOrganiser/Partials/OrganiserHeaderSection.blade.php
resources/views/Public/ViewOrganiser/Partials/OrganiserSocialSection.blade.php

As discussed on Twitter (Feb 13, 2021, 12:30 AM AEST):
>[Security Issue] - Self XSS via organizer name
>1. Install attendize
>2. Create a new organizer
>3. Insert your name as ><svg onload=alert(1)>
>4. Self XSS will trigger
> [Security Issue] - Ability to view the number of remaining ticket
>Hi! The endpoint /e/1/checkout allows the user to order a ticket. However upon selecting the value of ticket greater that 30, it returns the number of remaining ticket
>Steps to produce
>1. As owner setup an event
>2. As attacker open a proxy
>3. Go to event link
>4. Hit the register button and edit the value of ticket_1 to 31
>
>Request
> _token=wToBZ94jsNSsJKD2XL4SDjFprKNt06YHTjgcn0Ao&tickets%5B%5D=1&ticket_1=31&is_embedded=0
> Response
> {"status":"error","messages":{"ticket_1":["The maximum …

Address security issue reported by @jrckmcsb fixes #881

---

app/Http/Controllers/EventAttendeesController.php

Fixing issue #902: wrong import name

---

config/app.php
public/assets/stylesheet/application-rtl.css
public/assets/stylesheet/application-rtl.less
resources/views/Shared/Layouts/Master.blade.php

Add RTL languages support and make styles.

add RTL languages support

---

public/assets/stylesheet/application-rtl.css
public/assets/stylesheet/application-rtl.less

I've edited some styles for RTL support

fix some rtl styles

---

app/Services/PaymentGateway/StripeSCA.php
resources/views/Public/ViewEvent/Partials/PaymentStripeSCA.blade.php

Hello!
I'm actively using Attendize for two events, I've ran into this issue where refunding with Stripe SCA payment gateway does not work and hangs on for too long.
We also had issues where Stripe SCA was charging customers multiple times.
This was the error produced in Stripe 
An extract of the error text
```
"error": {
"code": "payment_intent_unexpected_state",
"doc_url": "https://stripe.com/docs/error-codes/payment-intent-unexpected-state",
"message": "You cannot cancel this PaymentIntent because it has a status of succeeded. Only a PaymentIntent with one of the following statuses may be canceled: requires_payment_method, requires_capture, requires_confirmation, requires_action, processing.",
```
Changing the method from ```cancel``` to ```refund``` solved the problem.
This is the …

Fix StripeSCA not refunding and charging multiple times

---

app/Http/Controllers/EventController.php
app/Http/Controllers/EventCustomizeController.php
database/factories/Event.php

@johannac this might be critical since changes proposed by this pr https://github.com/Attendize/Attendize/pull/970 weren't complete which broke existing tests.

fix: tests after https://github.com/Attendize/Attendize/pull/970

---

app/Models/Organiser.php

open_basedir in effect currently breaks organiser-page and ticket creation
i just swapped file-checks to test for the local one first
see https://github.com/Attendize/Attendize/issues/1036#issuecomment-1288177215

fix open_basedir restriction
